services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
    ports: ["5433:5432"]
    volumes:
      - postgres_data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3.13-management
    environment:
      RABBITMQ_DEFAULT_USER: bookstore
      RABBITMQ_DEFAULT_PASS: bookstore123
    ports: ["5672:5672", "15672:15672"]

  user-service:
    build: ./user-service
    depends_on:
      - postgres
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      JWT_SECRET: bookstore-jwt-secret
      AUTH_ADMIN_TOKEN: bookstore-auth-admin-token
      AUTH_ADMIN_USERNAME: admin
      AUTH_ADMIN_EMAIL: admin@bookstore.local
      AUTH_ADMIN_PASSWORD: Admin@123456
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py seed_admin; python manage.py runserver 0.0.0.0:8000"
    ports: ["8012:8000"]

  product-service:
    build: ./product-service
    depends_on:
      - postgres
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py seed_all_products; python manage.py runserver 0.0.0.0:8000"
    ports: ["8002:8000"]

  cart-service:
    build: ./cart-service
    depends_on:
      - postgres
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    ports: ["8003:8000"]

  order-service:
    build: ./order-service
    depends_on:
      - postgres
      - product-service
      - payment-service
      - shipping-service
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    ports: ["8005:8000"]

  shipping-service:
    build: ./shipping-service
    depends_on:
      - postgres
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    ports: ["8006:8000"]

  payment-service:
    build: ./payment-service
    depends_on:
      - postgres
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    ports: ["8007:8000"]

  ai-service:
    build: ./ai-service
    depends_on:
      - rabbitmq
      - order-service
      - product-service
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      RABBITMQ_URL: amqp://bookstore:bookstore123@rabbitmq:5672/
      REVIEW_EVENT_QUEUE: review.events
      NEO4J_URI: bolt://host.docker.internal:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: neo4j12345
      NEO4J_DATABASE: neo4j
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports: ["8021:8000"]

  ai-service-worker:
    build: ./ai-service
    depends_on:
      - ai-service
      - rabbitmq
    environment:
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      RABBITMQ_URL: amqp://bookstore:bookstore123@rabbitmq:5672/
      REVIEW_EVENT_QUEUE: review.events
      AISERVICE_URL: http://ai-service:8000
    command: python app/worker.py

  api-gateway:
    build: ./api-gateway
    depends_on:
      - postgres
      - user-service
      - cart-service
      - product-service
      - order-service
      - ai-service
    environment:
      AUTH_SERVICE_URL: http://user-service:8000
      SERVICE_SHARED_TOKEN: bookstore-internal-token
      AUTH_ADMIN_TOKEN: bookstore-auth-admin-token
      AI_SERVICE_URL: http://ai-service:8000
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tho17092004
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
    command: sh -c "python manage.py migrate --noinput; python manage.py runserver 0.0.0.0:8000"
    ports: ["8016:8000"]

volumes:
  postgres_data: {}
