from django.contrib import admin
from django.urls import path

from .views import (
    ai_dashboard,
    admin_users,
    add_cart_item,
    book_list,
    cart_lookup,
    create_customer,
    dashboard,
    create_order,
    create_promotion,
    create_review,
    customer_list,
    delete_book,
    delete_cart_item,
    favorite_products,
    home,
    login_view,
    logout_view,
    ops_metrics,
    ops_traces,
    product_detail,
    register_view,
    save_book,
    service_health,
    shop,
    sync_catalog,
    toggle_favorite,
    update_book_price,
    update_cart_item,
    view_cart,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home),
    path('dashboard/', dashboard),
    path('auth/login/', login_view),
    path('auth/register/', register_view),
    path('auth/logout/', logout_view),
    path('shop/', shop),
    path('shop/<int:product_id>/', product_detail),
    path('admin/users/', admin_users),
    path('staff/books/', book_list),
    path('staff/health/', service_health),
    path('staff/ai/dashboard/', ai_dashboard),
    path('staff/ops/metrics/', ops_metrics),
    path('staff/ops/traces/', ops_traces),
    path('staff/books/save/', save_book),
    path('staff/books/<int:book_id>/price/', update_book_price),
    path('staff/books/<int:book_id>/promotions/add/', create_promotion),
    path('staff/books/<int:book_id>/delete/', delete_book),
    path('staff/catalog/sync/', sync_catalog),
    path('customers/', customer_list),
    path('customers/create/', create_customer),
    path('customer/cart/', cart_lookup),
    path('customer/<int:customer_id>/favorites/', favorite_products),
    path('customer/favorites/<int:product_id>/toggle/', toggle_favorite),
    path('customer/cart/<int:customer_id>/', view_cart),
    path('customer/cart/<int:customer_id>/items/add/', add_cart_item),
    path('customer/cart/<int:customer_id>/items/<int:item_id>/update/', update_cart_item),
    path('customer/cart/<int:customer_id>/items/<int:item_id>/delete/', delete_cart_item),
    path('customer/cart/<int:customer_id>/order/', create_order),
    path('customer/cart/<int:customer_id>/review/', create_review),
]